backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', lambda req: redirect('/bewertungstool/')),
    path('admin/', admin.site.urls),
    path('bewertungstool/', include('polls_cms_integration.urls', namespace="polls")), # Link all the other urls that are in the polls_cms_integration url file
    # Rute to all the pages related with reseting the password
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'), name='password_reset_complete'),
    # Rute to all the pages related with the confirmation of email
    path('email_sent/', auth_views.PasswordResetDoneView.as_view(template_name='confirmation_email/email_sent.html'), name='email_sent'),
    path('email_confirmed/', auth_views.PasswordResetDoneView.as_view(template_name='confirmation_email/email_confirmed.html'), name='email_confirmed'),
    path('link_invalid/', auth_views.PasswordResetDoneView.as_view(template_name='confirmation_email/link_invalid.html'), name='link_invalid'),

]

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

urlpatterns.append(path('', include('cms.urls')))

# the new django admin sidebar is bad UX in django CMS custom admin views.
admin.site.enable_nav_sidebar = False

polls_cms_integration/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    # Default rute that loads the index function in views.py
    path('', views.IndexView, name='index'),
    # Rute to the sign up page
    path("register/", views.register, name='register'),
    # Rute to activation page after confirming the email
    path('activate/<slug:uidb64>/<slug:token>/',views.activate, name='activate'),
    # Rute to the log in page
    path("login_user/", views.login_user, name="login_user"),
    # Rute to the log out page
    path("logout_user/", views.logout_user, name="logout_user"),
    # Rute to the show the users register to delete page
    path("show_delete_user/", views.show_delete_user, name="show_delete_user"),
    # Rute to the delete user page
    path("delete_user/", views.delete_user, name="delete_user"),
    # Rute to reset the password
    path("password_reset/", views.password_reset_request, name="password_reset"),
    # Rute to the list of workshops page
    path("list_workshop/", views.list_workshop, name="list_workshop"),
    # Rute to the creation of workshops page
    path("create_workshop/", views.create_workshop, name="create_workshop"),
    # Rute to save the workshops page
    path("save_workshop/", views.save_workshop, name="save_workshop"),
    # Rute to introduction page
    path('intro/', views.intro, name='intro'),
    # Rute to first page for defining setting and participants
    path('setting/', views.setting_view, name='setting'),
    # Rute to first page for saving setting and participants
    path('save_setting/', views.save_setting, name='save_setting'),
    # Rute to page with questions 
    path('questions/<str:category>/<int:question_id>/', views.question_view, name='questions'), 
    # Rute to function that goes from one question to another 
    path('questions/<str:category>/<int:question_id>/next_ques/', views.next_ques, name='next_ques'),
    # Rute to function that goes from one question to previous 
    path('questions/<str:category>/<int:question_id>/prev_ques_lang/', views.prev_ques_lang, name='prev_ques_lang'),
    # Rute to function that skip one question
    path('questions/<str:category>/<int:question_id>/skip_ques/', views.skip_ques, name='skip_ques'),
    # Rute to function that shows skipped question
    path('questions/show_skip_ques/', views.show_skip_ques, name='show_skip_ques'), 
    # Rute to function that shows  the next skipped question
    path('questions/next_skip_ques/<str:category>/<int:question_id>/', views.next_skip_ques, name='next_skip_ques'),
    # Rute to skip a question inside the skipped question section
    path('questions/skip_skip_ques/', views.skip_skip_ques, name='skip_skip_ques'),
    # Rute to evaluation page
    path('evaluation/', views.evaluation, name='evaluation'),
    # Rute to create and download PDF page
    path('create_pdf/', views.create_pdf, name='create_pdf'),

    

]

backend/templates/confirmation_email/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Bitte klicken Sie auf den unten stehenden Link, um Ihre Anmeldung zu bestätigen:

http://{{ domain }}{% url 'polls:activate' uidb64=uid token=token %}
{% endautoescape %}

backend/templates/confirmation_email/email_confirmed.html
{% extends 'polls/base.html' %}


{% block content %}

<div class="background" style="text-align: center;">
	<!--Password reset sent-->
	<div class="container p-5">
  	<h1>Bestätigte E-Mail</h1>
		<hr>
		<p style="text-align: left; font-size: 20px;"> Vielen Dank für Ihre E-Mail-Bestätigung. Jetzt können Sie sich in Ihr Konto einloggen.</p>
        <br>                
        <a class="button" href="{% url 'polls:login_user' %}" role="button">Anmelden</a>
  </div>
</div>


{% endblock %}

backend/templates/confirmation_email/email_sent.html
{% extends 'polls/base.html' %}


{% block content %}

<div class="background" style="text-align: center;">
	<!--Password reset sent-->
	<div class="container p-5">
  	<h1>E-Mail-Bestätigung</h1>
		<hr>
		<p style="text-align: left; font-size: 20px;"> Bitte bestätigen Sie Ihre E-Mail-Adresse, um die Registrierung abzuschließen.</p>
  </div>
</div>


{% endblock %}

backend/templates/confirmation_email/link_invalid.html
{% extends 'polls/base.html' %}


{% block content %}

<div class="background" style="text-align: center;">
	<!--Password reset sent-->
	<div class="container p-5">
  	<h1>Bestätigte E-Mail</h1>
		<hr>
		<p style="text-align: left; font-size: 20px;"> Vielen Dank für Ihre E-Mail-Bestätigung. Jetzt können Sie sich in Ihr Konto einloggen.</p>
        <br>                
        <a class="button" href="{% url 'polls:register' %}" role="button">Register</a>
  </div>
</div>


{% endblock %}