backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', lambda req: redirect('/bewertungstool/')),
    path('admin/', admin.site.urls),
    path('bewertungstool/', include('polls_cms_integration.urls', namespace="polls")), # Link all the other urls that are in the polls_cms_integration url file
    # Rute to all the pages related with reseting the password
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'), name='password_reset_complete'),
    # Rute to all the pages related with the confirmation of email
    path('email_sent/', auth_views.PasswordResetDoneView.as_view(template_name='confirmation_email/email_sent.html'), name='email_sent'),
    path('email_confirmed/', auth_views.PasswordResetDoneView.as_view(template_name='confirmation_email/email_confirmed.html'), name='email_confirmed'),
    path('link_invalid/', auth_views.PasswordResetDoneView.as_view(template_name='confirmation_email/link_invalid.html'), name='link_invalid'),

]

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

urlpatterns.append(path('', include('cms.urls')))

# the new django admin sidebar is bad UX in django CMS custom admin views.
admin.site.enable_nav_sidebar = False

polls_cms_integration/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    # Default rute that loads the index function in views.py
    path('', views.IndexView, name='index'),
    # Rute to the sign up page
    path("register/", views.register, name='register'),
    # Rute to activation page after confirming the email
    path('activate/<slug:uidb64>/<slug:token>/',views.activate, name='activate'),
    # Rute to the log in page
    path("login_user/", views.login_user, name="login_user"),
    # Rute to the log out page
    path("logout_user/", views.logout_user, name="logout_user"),
    # Rute to the show the users register to delete page
    path("show_delete_user/", views.show_delete_user, name="show_delete_user"),
    # Rute to the delete user page
    path("delete_user/", views.delete_user, name="delete_user"),
    # Rute to reset the password
    path("password_reset/", views.password_reset_request, name="password_reset"),
    # Rute to the list of workshops page
    path("list_workshop/", views.list_workshop, name="list_workshop"),
    # Rute to the creation of workshops page
    path("create_workshop/", views.create_workshop, name="create_workshop"),
    # Rute to save the workshops page
    path("save_workshop/", views.save_workshop, name="save_workshop"),
    # Rute to introduction page
    path('intro/', views.intro, name='intro'),
    # Rute to first page for defining setting and participants
    path('setting/', views.setting_view, name='setting'),
    # Rute to first page for saving setting and participants
    path('save_setting/', views.save_setting, name='save_setting'),
    # Rute to page with questions 
    path('questions/<str:category>/<int:question_id>/', views.question_view, name='questions'), 
    # Rute to function that goes from one question to another 
    path('questions/<str:category>/<int:question_id>/next_ques/', views.next_ques, name='next_ques'),
    # Rute to function that goes from one question to previous 
    path('questions/<str:category>/<int:question_id>/prev_ques_lang/', views.prev_ques_lang, name='prev_ques_lang'),
    # Rute to function that skip one question
    path('questions/<str:category>/<int:question_id>/skip_ques/', views.skip_ques, name='skip_ques'),
    # Rute to function that shows skipped question
    path('questions/show_skip_ques/', views.show_skip_ques, name='show_skip_ques'), 
    # Rute to function that shows  the next skipped question
    path('questions/next_skip_ques/<str:category>/<int:question_id>/', views.next_skip_ques, name='next_skip_ques'),
    # Rute to skip a question inside the skipped question section
    path('questions/skip_skip_ques/', views.skip_skip_ques, name='skip_skip_ques'),
    # Rute to evaluation page
    path('evaluation/', views.evaluation, name='evaluation'),
    # Rute to create and download PDF page
    path('create_pdf/', views.create_pdf, name='create_pdf'),

    

]

backend/templates/polls/account_activation_email.html
{% autoescape off %}
Hallo {{ user.username }},

Bitte klicken Sie auf den folgenden Link, um Ihre Anmeldung zu bestätigen:

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

backend/templates/polls/base.html
{% extends 'base.html' %}

{% block content %}
    {% block polls_content %}
    {% endblock %}
{% endblock %}

backend/templates/polls/delete_user.html
{% extends 'polls/base.html' %}

{% block polls_content %} <!-- Block for the html logic -->
<div class="logout_sec">
    <a class="nav-link" href="{% url 'polls:logout_user' %}">LOGOUT</a>
</div>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %} <!-- we can use this simbol (double bracket) to introduce a variable from the python file-->

<div class="background" style="text-align: center;">
    <h1>Benutzer löschen</h1>
    <br>
    
    <form action="{% url 'polls:delete_user'%}" method="post">
        {% csrf_token %}

        <div class="grid-workshop">
            <div style="font-weight: bold;">Name</div>
            <div style="font-weight: bold;">Workshops</div>
            <div style="font-weight: bold;">Auswahl</div>
        
            {% for user in Users %}
            
                <div>
                    <label for="{{user.username}}">{{user.username}}</label>
                </div>
                
                <div>
                    {% for workshop in WorkshopList %}
                        {% if user.username ==  workshop.user_name %}
                            <label>{{workshop.workshop_name}} ({{workshop.workshop_date}})</label><br/>
                        {% endif %}
                    {% endfor %}
                </div> 

                <div>
                    <input type="radio" name="user_id" id="{{user.username}}" value="{{user.username}}" />
                </div>
            {% endfor %}
        </div>
        <br/>

        <div id = "show_pass_delete_user" >
            <label for="password" style="font-size: 20px; margin-left: -250px;">Bitte geben Sie das Kennwort dieses Benutzers ein, um ihn zu löschen</label><br />
            <input type="password" class="textarea_register" name="password" id="password_text" placeholder="Kennwort eingeben"><br>
        </div>
        
        <br>
        <input id="delete_button_user" type="submit" name="delete_user" value="Benutzer Löschen" class="button_red"/>
        <a class="button_brown" href="{% url 'polls:login_user' %}" role="button">Anmelden</a>
        <br /><br />

        <div class="form-group">
            {% for message in messages %}
            <div class="alert alert-danger" role="alert">
                {{message}}
            </div>
            {% endfor %}
        </div>
    </form>
</div>

{% endblock %}

backend/templates/polls/evaluation.html
{% extends 'polls/base.html' %}

{% block polls_content %}
<div class="logout_sec">
    <a class="nav-link" href="{% url 'polls:logout_user' %}">LOGOUT</a>
</div>
<div class="logout_mess">
    Klicken Sie hier, um sich von der Sitzung abzumelden, alle eingegebenen Daten werden gespeichert
</div>
<br/>
<form action="{% url 'polls:intro'%}" method="post">
    {% csrf_token %}
    <input id="button_back_intro" type="submit" name="back_intro_button" value="Zurück zur Einleitung" class="button" style="float: right;"/>
</form>
<br/><br/><br/><br/>

<div class="background" style="text-align: center;">
    <div class="container p-4">
	    <h1>Herzlichen Glückwunsch!</h1>
      <h2>Sie haben's geschafft</h2>
      <lottie-player src="https://lottie.host/d7055c0c-4a12-4481-b9c0-c2e9d5fceeee/DDOWEGha6e.json" background="#ebfff3" speed="1" style="width:400px; height: 400px; margin: 20px auto 0 auto;" loop autoplay direction="1" mode="normal"></lottie-player>
		  <hr>
      <div style="text-align: center; font-size: 20px;">
        <p>Klicken Sie auf die Button, um eine PDF-Datei mit den Ergebnissen des Workshops herunterzuladen.</p> 
        <br>                
        <a class="button" href="{% url 'polls:create_pdf' %}" role="button" style="text-align: center;">PDF herunterladen</a>
      </div>
    </div>
</div>


{% endblock %}

backend/templates/polls/list_workshop.html
{% extends 'polls/base.html' %}

{% block polls_content %} <!-- Block for the html logic -->
<div class="logout_sec">
    <a class="nav-link" href="{% url 'polls:logout_user' %}">LOGOUT</a>
</div>
<div class="logout_mess">
    Klicken Sie hier, um sich von der Sitzung abzumelden, alle eingegebenen Daten werden gespeichert
</div>
<br/>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %} <!-- we can use this simbol (double bracket) to introduce a variable from the python file-->

<div class="background" style="text-align: center;">
    <h1>Workshop Liste</h1>
    <br>
    <form action="{% url 'polls:intro'%}" method="post">
        {% csrf_token %}

        <div class="grid-workshop">
            <div style="font-weight: bold;">Name</div>
            <div style="font-weight: bold;">Datum</div>
            <div style="font-weight: bold;">Auswahl</div>
            {% for workshop in WorkshopList %}
    
                <div>
                    <label for="{{workshop.workshop_id}}">{{workshop.workshop_name}}</label>
                </div>
                
                <div>
                    <label>{{workshop.workshop_date}}</label>
                </div> 

                <div>
                    <input type="radio" name="workshop_id" id="{{workshop.workshop_id}}" value="{{workshop.workshop_id}}" />
                </div>
            {% endfor %} 
        </div>
        
        <br>
        <a class="button_brown" href="{% url 'polls:create_workshop' %}" role="button">Neuen Workshop erstellen</a>
        <input id="delete_button_listWS" type="submit" name="delete_workshop_button" value="Workshop Löschen" class="button_red"/>
        <input id="next_button_listWS" type="submit" name="intro_workshop" value="Weiter" class="button"/>
    </form>
</div>

{% endblock %}

backend/templates/polls/login.html
{% extends 'polls/base.html' %}

{% block polls_content %} <!-- Block for the html logic -->

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div class="background" style="text-align: center;">
    <form action="{% url 'polls:login_user'%}" method="post">
        {% csrf_token %}

        <h1>ANMELDEN</h1>
        <hr />

        <div class="grid-registration">
            <div>
                <label for="username" style="font-size: 20px;">Benutzername</label> <br />
                <input type="textarea" class="textarea_register" name="username" id="username" placeholder="Benutzernamen eingeben">
            </div>

            <div>
                <label for="password" style="font-size: 20px;">Kennwort</label><br />
                <input type="password" class="textarea_register" name="password" id="password" placeholder="Kennwort eingeben"><br>
                <a href="{% url 'polls:password_reset' %}" style="font-size: 18px;">Passwort vergessen?</a>
            </div>
        </div>
        
        <br /><br />
        <a class="button_brown" href="{% url 'polls:register' %}" role="button" id="register_button">Registrieren</a>
        <input id="anmelden_button" type="submit" value="Anmelden" class="button"/>
        <br /><br />
        <a class="button_red" href="{% url 'polls:show_delete_user' %}" role="button">Benutzer löschen</a>
        <br />
        <input type="hidden" id="email_host_var" name="email_host_var" value="{{email_host}}">
        
        <div class="form-group">
            {% for message in messages %}
            <div class="alert alert-danger" role="alert">
                {{message}}
            </div>
            {% endfor %}
        </div>
    </form>
</div>

{% endblock %}

backend/templates/polls/question.html
{% extends 'polls/base.html' %}

{% block polls_content %} <!-- Block for the html logic -->
<div class="logout_sec">
    <a class="nav-link" href="{% url 'polls:logout_user' %}">LOGOUT</a>
</div>
<div class="logout_mess">
    Klicken Sie hier, um sich von der Sitzung abzumelden, alle eingegebenen Daten werden gespeichert
</div>
<br/>
<form action="{% url 'polls:intro'%}" method="post">
    {% csrf_token %}
    <input id="button_back_intro" type="submit" name="back_intro_button" value="Zurück zur Einleitung" class="button" style="float: right;"/>
</form>
<br/><br/><br/><br/>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %} <!-- we can use this simbol (double bracket) to introduce a variable from the python file-->

<div class="background">
    <h1 style="text-align: center;">Fragebogen</h1>
    <br/>
    <div class="grid_question">

        <div class="grid-item_question question_item1">
            <!--Go back button-->
            <form action="{% url 'polls:prev_ques_lang' category question_id %}" method="post"> 
                {% csrf_token %}
                <input id="prev_button" type="submit" value="&#x226A" class="button_brown" title="Vorherige Frage" style="font-size: 30px; padding: 10px 20px; margin: 20px 0 0 0;"/> 
            </form>
        </div>

        <div class="grid-item_question question_item2">        
            <!-- We display a different question depending on the category-->
            {% if category == "economy" %}
                {% if mouse_over.economy == "" %}
                    <h1>{{question.economy}}</h1>
                {% else %}
                    <h1 title="{{mouse_over.economy}}">{{question.economy}} &#9432;</h1>
                {% endif %}
            {% elif category == "care" %}
                 {% if mouse_over.care == "" %}
                     <h1>{{question.care}}</h1>
                 {% else %}
                     <h1 title="{{mouse_over.care}}">{{question.care}} &#9432;</h1>
                 {% endif %}
            {% elif category == "technology" %}
                 {% if mouse_over.technology == "" %}
                     <h1>{{question.technology}}</h1>
                 {% else %}
                     <h1 title="{{mouse_over.technology}}">{{question.technology}} &#9432;</h1>
                 {% endif %}
            {% elif category == "embedding" %}
                 {% if mouse_over.embedding == "" %}
                     <h1>{{question.embedding}}</h1>
                 {% else %}
                     <h1 title="{{mouse_over.embedding}}">{{question.embedding}} &#9432;</h1>
                 {% endif %}
            {% elif category == "law" %}
                 {% if mouse_over.law == "" %}
                     <h1>{{question.law}}</h1>
                 {% else %}
                     <h1 title="{{mouse_over.law}}">{{question.law}} &#9432;</h1>
                 {% endif %}
            {% else %}
                 {% if mouse_over.ethics == "" %}
                     <h1>{{question.ethics}}</h1>
                 {% else %}
                     <h1 title="{{mouse_over.ethics}}">{{question.ethics}} &#9432;</h1>
                 {% endif %}
            {% endif %}
        </div> 

        <div class="grid-item_question question_item3">
            <!--Submit button to get to the next slide-->
            <input id="next_button" type="submit" value="&#x226B" class="button" form="question_form" title="Weiter" style="font-size: 30px; padding: 10px 20px; margin: 20px 0 0 0;"/> 
        </div>

        <div class="grid-item_question question_item4">
            {% if robot_name != "" %}
                <p>Bitte diskutieren Sie diese Frage in Bezug auf das ausgewählte robotische System namens <strong>{{robot_name}}</strong>.</p>
            {% endif %}
            <form action="{% url 'polls:next_ques' category question_id %}" method="post" id="question_form"> 
                {% csrf_token %}
                <div class="div_question_section">
                    <!--Radio buttons with 3 options (ja, ja aber, nein) for the last two we also need a comments section-->
                    {% if selected_option == "Ja" %}
                    <input type="radio" name="choice" id="choice_ja" value="Ja" checked/>
                    {% else %} 
                    <input type="radio" name="choice" id="choice_ja" value="Ja" />
                    {% endif %}
                    <label id="label_ja"><span class="circle_green"></span>Wir haben keinen Diskussionsbedarf</label><br /><br />

                    {% if selected_option == "Ja_aber" %}
                    <input type="radio" name="choice" id="choice_ja_aber" value="Ja_aber" checked/>
                    {% else %} 
                    <input type="radio" name="choice" id="choice_ja_aber" value="Ja_aber" />
                    {% endif %}
                    <label id="label_ja_aber"> <span class="circle_yellow"></span>In Bezug auf die Fragestellung geben wir folgenden Hinweis:</label><br />
                    <textarea id="text_jaaber" name="text_jaaber" placeholder="[Bitte erläutern/ begründen Sie hier. Ihre Daten werden automatisch gespeichert]" style="height:100px; width: 70%;" class="textarea_question">{{comment_jaaber}}</textarea><br>

                    {% if selected_option == "nein" %}
                    <input type="radio" name="choice" id="choice_nein" value="nein" checked/>
                    {% else %} 
                    <input type="radio" name="choice" id="choice_nein" value="nein" />
                    {% endif %}
                    <label id="label_nein" style="width: 95%;"> <span class="circle_red"></span>In Bezug auf die Fragestellung ist der Einsatz robotischer Systeme nicht möglich, weil… </label><br />
                    <textarea id="text_nein" name="text_nein" placeholder="[Bitte erläutern/ begründen Sie hier. Ihre Daten werden automatisch gespeichert]" style="height:100px; width: 70%;" class="textarea_question">{{comment_nein}}</textarea><br>
                    <div id= "nein_section">
                        <label> Folgende Bedingungen müssten für einen Einsatz erfüllt sein… (optional)</label><br>
                        <textarea id="text_unless" name="text_unless" placeholder="[Bitte erläutern/ begründen Sie hier. Ihre Daten werden automatisch gespeichert]" style="height:100px; width: 70%;" class="textarea_question">{{comment_unless}}</textarea><br><br>
                    </div>
                    
                </div>
                <br/>
                <!-- Button to clear all the selections-->
                <button id="clear_button" type="button" title="Nur die ausgewählten Elemente dieser Antwort löschen" class="button_red">Antwort löschen </button> 
            </form>
            <!--Skip question button-->
            <form action="{% url 'polls:skip_ques' category question_id %}" method="post" > 
                {% csrf_token %}
                <input id="skip_button" type="submit" value="Frage überspringen" style="float: right; margin-top: -60px;" class="button_brown"/> 
            </form>
            
        </div>

        <div class="grid-item_question question_item5">
            <label>&#x1F4C2; Unbeantwortet</label> <br/> 
            <label>&#x2705; Beantwortet</label> 
        </div>

        <div class="grid-item_question question_item6">
            <label class="label_right">{{n_ques_left}}</label><br/>
            <label class="label_right">{{n_ques_answered}}</label>
        </div>

        <div class="grid-item_question question_item7">
            <p> <strong>Kategorien</strong></p>
            {% if category == "care" %}
            <label class="category_label" style="background-color: #00af41;">Pflege</label><br/>
            {% else %}
            <label class="category_label">Pflege</label><br/>
            {% endif %}
            {% if category == "technology" %}
            <label class="category_label" style="background-color: #00af41;">Technik & Infrastruktur</label><br/>
            {% else %}
            <label class="category_label">Technik & Infrastruktur</label><br/>
            {% endif %}
            {% if category == "embedding" %}
            <label class="category_label" style="background-color: #00af41;">Institutionelle & gesellschaftliche Einbettung</label><br/>
            {% else %}
            <label class="category_label">Institutionelle & gesellschaftliche Einbettung</label><br/>
            {% endif %}
            {% if category == "law" %}
            <label class="category_label" style="background-color: #00af41;">Datenschutz & Recht</label><br/>
            {% else %}
            <label class="category_label">Datenschutz & Recht</label><br/>
            {% endif %}
            {% if category == "ethics" %}
            <label class="category_label" style="background-color: #00af41;">Ethik</label><br/>
            {% else %}
            <label class="category_label">Ethik</label><br/>
            {% endif %}
            {% if category == "economy" %}
            <label class="category_label" style="background-color: #00af41;">Ökonomie</label><br/>
            {% else %}
            <label class="category_label">Ökonomie</label><br/>            
            {% endif %}

        </div>

    </div>

</div>

{% endblock %}

backend/templates/polls/skipped_question.html
{% extends 'polls/base.html' %}

{% block polls_content %} <!-- Block for the html logic -->
<div class="logout_sec">
    <a class="nav-link" href="{% url 'polls:logout_user' %}">LOGOUT</a>
</div>
<div class="logout_mess">
    Klicken Sie hier, um sich von der Sitzung abzumelden, alle eingegebenen Daten werden gespeichert
</div>
<br/>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %} <!-- we can use this simbol (double bracket) to introduce a variable from the python file-->

<div class="background">
    <h1 style="text-align: center;">Fragebogen (übersprungene Fragen)</h1>
    <br/>
    <div class="grid_question">

        <div class="grid-item_question question_item1">
            <!--Go back button-->
            <!-- We don't allow for going back, but we leave the division to keep the template like in question.html-->
        </div>

        <div class="grid-item_question question_item2">
            {% if category == "economy" %}
                {% if mouse_over.economy == "" %}
                    <h1>{{question.question}}</h1> 
                {% else %}
                    <h1 title="{{mouse_over.economy}}">{{question.question}} &#9432;</h1>
                {% endif %}
            {% elif category == "care" %}
                 {% if mouse_over.care == "" %} 
                    <h1>{{question.question}}</h1>
                 {% else %} 
                    <h1 title="{{mouse_over.care}}">{{question.question}} &#9432;</h1>
                 {% endif %} 
            {% elif category == "technology" %}
                 {% if mouse_over.technology == "" %} 
                    <h1>{{question.question}}</h1> 
                 {% else %} 
                    <h1 title="{{mouse_over.technology}}">{{question.question}} &#9432;</h1>
                 {% endif %} 
            {% elif category == "embedding" %}
                 {% if mouse_over.embedding == "" %} 
                    <h1>{{question.question}}</h1> 
                 {% else %} 
                    <h1 title="{{mouse_over.embedding}}">{{question.question}} &#9432;</h1>
                 {% endif %} 
            {% elif category == "law" %}
                 {% if mouse_over.law == "" %} 
                    <h1>{{question.question}}</h1> 
                 {% else %} 
                    <h1 title="{{mouse_over.law}}">{{question.question}} &#9432;</h1>
                 {% endif %} 
            {% else %}
                 {% if mouse_over.ethics == "" %} 
                    <h1>{{question.question}}</h1> 
                 {% else %} 
                    <h1 title="{{mouse_over.ethics}}">{{question.question}} &#9432;</h1>
                 {% endif %} 
            {% endif %}        
          
        </div> 

        <div class="grid-item_question question_item3">
            <!--Submit button to get to the next slide-->
            <input id="next_button" type="submit" value="&#x226B" class="button" form="question_skip_form" title="Weiter" style="font-size: 30px; padding: 10px 20px; margin: 20px 0 0 0;"/> <!--value="Weiter"-->
        </div>

        <!--<div class="grid-item_question question_item3">
            Skip question button
            <form action="{% url 'polls:skip_skip_ques' %}" method="post" > 
                {% csrf_token %}
                <input id="skip_button" type="submit" value="Frage überspringen" style="float: right; margin: 20px 0 0 0;"/>
            </form>
        </div>-->

        <div class="grid-item_question question_item4">

            <form action="{% url 'polls:next_skip_ques' category question_id %}" method="post" id="question_skip_form"> 
                {% csrf_token %}
                <div class="div_question_section">
                    <!--Radio buttons with 3 options (ja, ja aber, nein) for the last two we also need a comments section-->
                    {% if selected_option == "Ja" %}
                    <input type="radio" name="choice" id="choice_ja" value="Ja" checked/>
                    {% else %} 
                    <input type="radio" name="choice" id="choice_ja" value="Ja" />
                    {% endif %}
                    <label id="label_ja" ><span class="circle_green"></span>Wir haben keinen Diskussionsbedarf</label><br /><br />

                    {% if selected_option == "Ja_aber" %}
                    <input type="radio" name="choice" id="choice_ja_aber" value="Ja_aber" checked/>
                    {% else %} 
                    <input type="radio" name="choice" id="choice_ja_aber" value="Ja_aber" />
                    {% endif %}
                    <label id="label_ja_aber"><span class="circle_yellow"></span>In Bezug auf die Fragestellung geben wir folgenden Hinweis:</label><br />
                    <textarea id="text_jaaber" name="text_jaaber" placeholder="[Bitte erläutern/ begründen Sie hier. Ihre Daten werden automatisch gespeichert]" style="height:100px; width: 70%;" class="textarea_question">{{comment_jaaber}}</textarea><br>

                    {% if selected_option == "nein" %}
                    <input type="radio" name="choice" id="choice_nein" value="nein" checked/>
                    {% else %} 
                    <input type="radio" name="choice" id="choice_nein" value="nein" />
                    {% endif %}
                    <label id="label_nein" style="width: 95%;"><span class="circle_red"></span>In Bezug auf die Fragestellung ist der Einsatz robotischer Systeme nicht möglich, weil…</label><br />
                    <textarea id="text_nein" name="text_nein" placeholder="[Bitte erläutern/ begründen Sie hier. Ihre Daten werden automatisch gespeichert]" style="height:100px; width: 70%;" class="textarea_question">{{comment_nein}}</textarea><br>
                    <div id= "nein_section">
                        <label> Folgende Bedingungen müssten für einen Einsatz erfüllt sein… (optional)</label><br>
                        <textarea id="text_unless" name="text_unless" placeholder="[Bitte erläutern/ begründen Sie hier. Ihre Daten werden automatisch gespeichert]" style="height:100px; width: 70%;" class="textarea_question">{{comment_unless}}</textarea><br><br>
                    </div>
                </div>
                <br/>
                <!-- Button to clear all the selections-->
                <button id="clear_button" type="button" title="Nur die ausgewählten Elemente dieser Antwort löschen" class="button_red">Antwort löschen </button> 
            </form>
            <form action="{% url 'polls:skip_skip_ques' %}" method="post" > 
                {% csrf_token %}
                <input id="skip_button" type="submit" value="Frage überspringen" style="float: right; margin-top: -60px;" class="button_brown"/> <!--value="&#x226B" style="margin: 20px 0 0 0;"-->
            </form>
        </div>

        <div class="grid-item_question question_item5">
            <!-- <label>&#x1F4C2; Alle Fragen</label> <br/> -->
            <label>&#x1F4C2; Unbeantwortet</label> <br/> <!--&#x274D-->
            <label>&#x2705; Beantwortet</label> 
        </div>

        <div class="grid-item_question question_item6">
            <!-- <label class="label_right">{{n_ques_total}}</label> <br/> -->
            <label class="label_right">{{n_ques_left}}</label><br/>
            <label class="label_right">{{n_ques_answered}}</label>
        </div>

        <div class="grid-item_question question_item7">
            <p> <strong>Kategorien</strong></p>
            <!-- <input type="radio" name="category_ques" id="ques_economy" value="economy" /> -->
            {% if category == "care" %}
            <label class="category_label" style="background-color: #00af41;">Pflege</label><br/>
            {% else %}
            <label class="category_label">Pflege</label><br/>
            {% endif %}
            {% if category == "technology" %}
            <label class="category_label" style="background-color: #00af41;">Technik & Infrastruktur</label><br/>
            {% else %}
            <label class="category_label">Technik & Infrastruktur</label><br/>
            {% endif %}
            {% if category == "embedding" %}
            <label class="category_label" style="background-color: #00af41;">Institutionelle & gesellschaftliche Einbettung</label><br/>
            {% else %}
            <label class="category_label">Institutionelle & gesellschaftliche Einbettung</label><br/>
            {% endif %}
            {% if category == "law" %}
            <label class="category_label" style="background-color: #00af41;">Datenschutz & Recht</label><br/>
            {% else %}
            <label class="category_label">Datenschutz & Recht</label><br/>
            {% endif %}
            {% if category == "ethics" %}
            <label class="category_label" style="background-color: #00af41;">Ethik</label><br/>
            {% else %}
            <label class="category_label">Ethik</label><br/>
            {% endif %}
            {% if category == "economy" %}
            <label class="category_label" style="background-color: #00af41;">Ökonomie</label><br/>
            {% else %}
            <label class="category_label">Ökonomie</label><br/>
            {% endif %}

        </div>

    </div>

</div>

{% endblock %}